language: ruby

rvm:
  - 2.2.5

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site

branches:
  only:
    - develop
    - master

