language: ruby

rvm:
  - 2.2.5

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install
  - gem install html-proofer
script: jekyll build
#after_script: htmlproofer ./_site
