# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liri
email: info@liri.io
description: > # this means to ignore newlines until "baseurl:"
  An OS and apps built with modern design and features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liri.io" # the base hostname & protocol for your site
github:
  repo: "https://github.com/lirios/lirios.github.io"
social:
  github: lirios
  googleplus:
    page: 100355783508323292342
    community: 115722443491803015565
  twitter:
  facebook:
  youtube:
team:
  - name: Pier Luigi Fiorini
    occupation: Software developer
    location: Italy
    avatar: images/avatars/avatar_pier.png
    twitter: https://twitter.com/@plfiorini
    googleplus: https://plus.google.com/+PierLuigiFiorini
    github: https://github.com/plfiorini
  - name: Micheal Spencer
    occupation: Software developer and CS student
    location: USA
    avatar: images/avatars/avatar_michael.jpg
    twitter: https://twitter.com/iBeliever316
    googleplus: https://plus.google.com/+MichaelSpencer
    github: https://github.com/iBeliever
  - name: Tim Süberkrüb
    occupation: Student
    location: Germany
    avatar: images/avatars/avatar_tim.png
    twitter: https://twitter.com/@TimSueberkrueb
    googleplus: https://plus.google.com/+TimS%C3%BCberkr%C3%BCbDE/
    github: https://github.com/tim-sueberkrueb/
  - name: Pierre Jacquier
    occupation: Student at UTBM
    location: France
    avatar: images/avatars/avatar_pierre.jpg
    twitter: https://twitter.com/PierreJacquier
    googleplus: https://plus.google.com/+PierreJacquierFR/
    github: https://github.com/pierremtb
  - name: Andrew Penkrat
    location: Russia
  - name: Nick Germaine
    location: Canada
  - name: Pierre-Yves Siret
    location: France
  - name: Ziga Patacko Koderman
    location: Slovenia

# Build settings
markdown: kramdown
theme: minima
gem:
  - jekyll-sitemap
